/**
 * Словари интерфейса.
 *
 * Здесь нет ни React, ни Telegram — только данные и подстановка. Благодаря
 * этому переводы проверяются тестами вместе с серверным кодом: тест следит,
 * что у каждого кода события и ошибки есть фраза на обоих языках.
 *
 * Значение словаря — либо строка с подстановками вида {name}, либо функция,
 * если фраза зависит от числа: в русском три формы, в английском две.
 */

/** Русские числительные: 1 игрок, 2 игрока, 5 игроков. */
function ruPlural(n, one, few, many) {
  const mod10 = n % 10;
  const mod100 = n % 100;
  if (mod10 === 1 && mod100 !== 11) return one;
  if (mod10 >= 2 && mod10 <= 4 && (mod100 < 12 || mod100 > 14)) return few;
  return many;
}

const enPlural = (n, one, many) => (n === 1 ? one : many);

const ru = {
  'app.title': 'Мафия',
  'app.tagline': 'Классическая игра для компании 5–12 человек',
  'app.hello': 'Привет, {name}',
  'app.connecting': 'Подключаюсь…',
  'app.reconnecting': 'Переподключаюсь…',
  'app.offline': 'Связь потеряна. Восстанавливаю соединение…',
  'app.locked': 'Не удалось подтвердить вход через Telegram.\nОткройте игру кнопкой в боте',
  'app.voiceHint': 'Обсуждать удобнее голосом — включите звонок в Telegram и играйте параллельно.',

  'common.yes': 'Да',
  'common.no': 'Нет',
  'common.enter': 'Войти',
  'common.leave': 'Выйти',
  'common.back': 'Назад',
  'common.ready': 'готов',
  'common.you': 'вы',
  'common.rules': 'Правила игры',
  'view.table': 'Стол',
  'view.list': 'Список',
  'common.hideRules': 'Скрыть правила',
  'common.channel': 'Подписаться на канал',
  'common.players': (n) => `${n} ${ruPlural(n, 'игрок', 'игрока', 'игроков')}`,
  'common.playersShort': (n) => `${n} ${ruPlural(n, 'игроке', 'игроках', 'игроках')}`,
  'common.alive': (n) => `${n} ${ruPlural(n, 'живой', 'живых', 'живых')}`,
  'common.rooms': (n) => `${n} ${ruPlural(n, 'комната', 'комнаты', 'комнат')}`,
  'common.sec': (n) => `${n} сек`,
  'common.min': (n) => `${n} мин`,

  'home.create': 'Создать комнату',
  'home.createNote': 'позвать друзей по коду',
  'home.openRooms': 'Открытые комнаты',
  'home.openRoomsBtn': 'Открытые комнаты',
  'home.roomsWaiting': (n) => `${n} ${['комната ждёт','комнаты ждут','комнат ждут'][n % 10 === 1 && n % 100 !== 11 ? 0 : (n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 12 || n % 100 > 14)) ? 1 : 2]}`,
  'home.roomsEmpty': 'пока пусто',
  'rooms.title': 'Открытые комнаты',
  'rooms.hint': 'Выберите комнату и заходите. Список обновляется сам.',
  'rooms.createOwn': 'Создать свою комнату',
  'home.noRooms': 'Сейчас открытых комнат нет.',
  'home.noRoomsHint': 'Создайте свою — её увидят другие.',
  'home.room': 'Комната {code}',
  'home.needMore': (n) => `не хватает ещё ${n} ${ruPlural(n, 'игрока', 'игроков', 'игроков')}`,
  'home.canStart': 'можно начинать',
  'home.orCode': 'Или по коду комнаты',
  'home.games': 'партий',
  'home.winrate': 'побед',

  'home.bots': 'Играть с ботами',
  'home.botsNote': 'сразу, без ожидания',
  'bots.title': 'Боты',
  'bots.add': 'Добавить бота',
  'bots.remove': 'Убрать бота',
  'bots.count': (n) => `${n} ${ruPlural(n, 'бот', 'бота', 'ботов')} за столом`,
  'bots.none': 'ботов нет',
  'bots.hint': 'Боты занимают свободные места и играют сами: ходят ночью, обсуждают и голосуют.',
  'bots.badge': 'бот',
  'bots.solo': 'Игра с ботами',

  // Реплики ботов в обсуждении: сервер шлёт код, фраза собирается здесь
  'bot.say.quiet': 'Что-то все притихли. Давайте по делу.',
  'bot.say.suspect': 'Мне не нравится, как ведёт себя {name}.',
  'bot.say.defend': 'За {name} я бы не голосовал, он весь день на виду.',
  'bot.say.agree': 'Согласен с предыдущим. Логика есть.',
  'bot.say.unsure': 'Пока не понимаю, за кого голосовать.',
  'bot.say.watch': 'Приглядитесь к {name}, он отмалчивается.',
  'bot.say.pressure': 'Давайте решать, время уходит.',
  'bot.say.nothing': 'У меня по этой ночи ничего нет.',

  'lobby.code': 'Код комнаты',
  'lobby.copy': 'Копировать',
  'lobby.copied': 'Скопирован',
  'lobby.kick': 'Убрать игрока',
  'lobby.invite': 'Пригласить друзей',
  'lobby.inviteText': 'Играем в мафию! Код комнаты: {code}',
  'lobby.players': 'Игроки',
  'lobby.of': 'из {max}',
  'lobby.waitingPlayer': 'Ждём игрока',
  'lobby.start': 'Начать игру',
  'lobby.waitHost': 'Ждём, пока создатель комнаты начнёт игру…',
  'lobby.settings': 'Настройки игры',
  'lobby.hideSettings': 'Скрыть настройки',
  'lobby.creator': 'создатель комнаты',
  'lobby.hostNoRole': 'ведущий, роли не получает',
  'lobby.offline': 'нет связи, ждём возвращения',
  'lobby.composition': 'Состав при {players}: {roles}',

  'set.host': 'Ведущий',
  'set.hostBot': 'Бот ведёт сам, вы играете',
  'set.hostHuman': 'Вы ведёте, роль не получаете',
  'set.bot': 'Бот',
  'set.me': 'Я',
  'set.public': '🌍 Открытая комната',
  'set.publicOn': 'Видна всем на главной, зайти может любой',
  'set.publicOff': 'Только по коду — играете со своими',
  'set.doctor': '💉 Доктор',
  'set.doctorHint': 'Ночью спасает одного игрока от убийства',
  'set.sheriff': '🔎 Комиссар',
  'set.sheriffHint': 'Ночью проверяет, мафия игрок или нет',
  'set.on': 'Есть',
  'set.off': 'Нет',
  'set.maxPlayers': 'Максимум игроков',
  'set.tie': 'При равенстве голосов',
  'set.tieRevote': 'Второй тур между лидерами',
  'set.tieNobody': 'Никто не выбывает',
  'set.tieRandom': 'Случайный из лидеров',
  'set.tieRevoteShort': '2-й тур',
  'set.tieNobodyShort': 'Никто',
  'set.tieRandomShort': 'Жребий',
  'set.night': 'Ночь',
  'set.discussion': 'Обсуждение',
  'set.voting': 'Голосование',
  'set.reveal': 'Открывать роль выбывших',
  'set.revealHint': 'Показывать, кем был погибший',

  'phase.roles': 'Раздача ролей',
  'phase.night': 'Ночь',
  'phase.day': 'Утро',
  'phase.discussion': 'Обсуждение',
  'phase.voting': 'Голосование',
  'phase.revote': 'Переголосовка',
  'phase.verdict': 'Приговор',
  'phase.ended': 'Игра окончена',

  'role.mafia': 'Мафия',
  'role.mafia.desc': 'Ночью вы вместе с подельниками выбираете жертву. Днём — притворяетесь мирным.',
  'role.sheriff': 'Комиссар',
  'role.sheriff.desc': 'Каждую ночь вы проверяете одного игрока и узнаёте, мафия он или нет.',
  'role.doctor': 'Доктор',
  'role.doctor.desc': 'Каждую ночь вы спасаете одного игрока. Если мафия выберет его — он выживет.',
  'role.civilian': 'Мирный житель',
  'role.civilian.desc': 'У вас нет ночных способностей. Ваше оружие — внимание и убеждение.',
  'role.host': 'Ведущий',
  'role.host.desc': 'Вы видите все роли и переключаете фазы. В голосовании не участвуете.',

  'game.dayN': 'День {n}',
  'game.nightN': 'Ночь {n}',
  'game.rememberRole': 'Запомните свою роль и никому её не показывайте',
  'game.partners': 'Ваши подельники',
  'game.partnersMarked': 'Ваши подельники отмечены красным.',
  'game.aloneMafia': 'Вы единственный мафиози. Действуйте осторожно.',
  'game.dealt': 'Раздача ролей',
  'game.wakeMafia': 'Разбудите мафию и комиссара',
  'game.nightMoves': 'Ночные ходы',
  'game.cityAsleep': 'Город спит',
  'game.pickVictim': 'Выберите жертву',
  'game.pickCheck': 'Проверьте одного игрока',
  'game.pickHeal': 'Кого будете спасать?',
  'game.youSleep': 'Вы спите. Дождитесь утра',
  'game.youSleepNote': 'Вы мирный житель — просто спите. Утром узнаете новости.',
  'game.watching': 'Вы наблюдаете. Город спит.',
  'game.mafiaTie': 'Если мафия выберет разные цели, погибнет тот, за кого больше голосов.',
  'game.mafiaChat': 'Тайный чат мафии…',
  'game.yourTarget': 'ваша цель',
  'game.checkSent': 'Проверка отправлена. Результат вы увидите утром.',
  'game.yourChecks': 'Ваши проверки',
  'game.isMafia': 'мафия',
  'game.notMafia': 'не мафия',
  'game.checkedMafia': '🔴 проверен: мафия',
  'game.checkedClean': '🟢 проверен: не мафия',
  'game.healedYesterday': 'лечили прошлой ночью — нельзя',
  'game.healing': 'вы лечите его',
  'game.healRule': 'Одного и того же нельзя лечить две ночи подряд. Себя лечить можно.',
  'game.healOn': 'Вы дежурите у постели. Если мафия придёт за ним — он выживет.',
  'game.beingHealed': '💉 лечат',
  'game.cityWakes': 'Город просыпается',
  'game.killedTonight': 'убит этой ночью',
  'game.executedByCity': 'казнён по решению города',
  'game.allSurvived': 'Этой ночью все выжили',
  'game.nobodyExecuted': 'Город никого не казнил',
  'game.savedYou': '💉 Мафия приходила за вами — вы успели вовремя. Об этом знаете только вы.',
  'game.savedName': '💉 Мафия приходила за {name} — вы успели вовремя. Об этом знаете только вы.',
  'game.discussFree': 'Обсуждайте — ведущий закончит фазу',
  'game.discussTimed': 'Обсуждайте, кто похож на мафию',
  'game.yourTheory': 'Ваша версия…',
  'game.deadSilent': 'Мёртвые не говорят',
  'game.readyToVote': 'Готов голосовать ({done}/{total})',
  'game.youReady': '✓ Вы готовы ({done}/{total}) — отменить',
  'game.votedOf': 'Проголосовали: {done} из {total}',
  'game.votedCount': 'Проголосовали {done} из {total}',
  'game.revoteNote': 'Голоса разделились поровну. Второй тур — только между кандидатами.',
  'game.revoteSub': 'Второй тур между кандидатами',
  'game.yourVote': 'ваш голос',
  'game.abstain': 'Воздержаться',
  'game.abstained': '✓ Вы воздержались',
  'game.candidateNote': 'Вы кандидат на выбывание и не голосуете в этом туре.',
  'game.verdictSub': 'Итог голосования',
  'game.whatHappened': 'Что произошло',
  'game.hostView': 'Вы ведущий: видите все роли и переключаете фазы.',
  'game.spectator': 'Вы выбыли из игры, но можете наблюдать до конца партии.',
  'game.inGame': 'в игре',
  'game.noSignal': 'нет связи',
  'game.host': 'ведущий',
  'game.diedNight': 'убит ночью',
  'game.diedVote': 'казнён городом',
  'game.noMessages': 'Сообщений пока нет.',
  'game.write': 'Написать…',

  'next.roles': 'Начать первую ночь →',
  'next.night': 'Разбудить город →',
  'next.day': 'Начать обсуждение →',
  'next.discussion': 'Перейти к голосованию →',
  'next.voting': 'Подвести итоги →',
  'next.revote': 'Подвести итоги →',
  'next.verdict': 'Начать ночь →',
  'next.default': 'Далее →',

  'over.mafiaWin': 'Победила мафия',
  'over.townWin': 'Победил город',
  'over.mafiaWinSub': 'Мафиози оказалось не меньше, чем мирных жителей',
  'over.townWinSub': 'Вся мафия выведена из игры',
  'over.youWon': '🎉 Вы в команде победителей',
  'over.youLost': 'В этот раз не сложилось',
  'over.mafiaTeam': 'Мафия ({n})',
  'over.townTeam': 'Город ({n})',
  'over.survived': ' · выжил',
  'over.again': 'Играть ещё раз',
  'over.waitHost': 'Ждём, начнёт ли создатель новую партию…',
  'over.toMenu': 'Выйти в меню',

  'rules.title': 'Правила',
  'rules.mafia': 'Мафия',
  'rules.mafiaText': 'знает своих и каждую ночь убивает одного жителя.',
  'rules.doctor': 'Доктор',
  'rules.doctorText': 'ночью спасает одного игрока — если мафия пришла за ним, он выживает.',
  'rules.sheriff': 'Комиссар',
  'rules.sheriffText': 'ночью проверяет одного игрока — мафия он или нет.',
  'rules.civil': 'Мирные жители',
  'rules.civilText': 'ищут мафию логикой и обсуждением.',
  'rules.counts': 'Мафии примерно треть от числа игроков: 5 игроков — 1 мафия, 6–8 — 2, 9–11 — 3, 12 — 4. Доктор и комиссар — по одному, включаются в настройках комнаты. Остальные — мирные.',
  'rules.healRule': 'Доктор не может лечить одного и того же две ночи подряд. Себя лечить можно.',
  'rules.night': 'Ночью',
  'rules.nightText': 'город спит, мафия договаривается в тайном чате и выбирает жертву, доктор кого-то спасает, комиссар проверяет игрока.',
  'rules.morning': 'Утром',
  'rules.morningText': 'объявляют погибшего.',
  'rules.day': 'Днём',
  'rules.dayText': 'все обсуждают и голосуют. Кто набрал больше голосов — выбывает. При равенстве голосов проходит переголосовка.',
  'rules.townWin': 'Мирные побеждают',
  'rules.townWinText': ', когда мафии не осталось.',
  'rules.mafiaWin': 'Мафия побеждает',
  'rules.mafiaWinText': ', когда её столько же, сколько мирных, или больше.',

  'comp.mafia': (n) => `${n} ${ruPlural(n, 'мафия', 'мафии', 'мафий')}`,
  'comp.sheriff': 'комиссар',
  'comp.doctor': 'доктор',
  'comp.civil': (n) => `${n} ${ruPlural(n, 'мирный', 'мирных', 'мирных')}`,

  'log.game_started': 'Игра началась. Раздача ролей.',
  'log.night_falls': 'Ночь {day}. Город засыпает.',
  'log.killed': ({ name, role }, t) =>
    role ? `Ночью убит ${name} (${t(`roleLower.${role}`)}).` : `Ночью убит ${name}.`,
  'log.nobody_died': 'Этой ночью никто не погиб.',
  'log.voting_started': 'Голосование началось.',
  'log.nobody_voted': 'Никто не проголосовал — город никого не казнил.',
  'log.tie_revote': 'Равное количество голосов: {names}. Переголосовка.',
  'log.tie_nobody': 'Голоса разделились поровну — никто не выбывает.',
  'log.executed': ({ name, role }, t) =>
    role ? `Городом казнён ${name} (${t(`roleLower.${role}`)}).` : `Городом казнён ${name}.`,
  'log.win_mafia': 'Мафия победила: мафиози не меньше, чем мирных жителей.',
  'log.win_town': 'Мирные жители победили: вся мафия выведена из игры.',

  'roleLower.mafia': 'мафия',
  'roleLower.sheriff': 'комиссар',
  'roleLower.doctor': 'доктор',
  'roleLower.civilian': 'мирный житель',

  'err.game_running': 'Игра уже идёт — присоединиться нельзя.',
  'err.game_over': 'Эта игра уже закончилась.',
  'err.room_full': 'В комнате нет свободных мест.',
  'err.bots_host_only': 'Ботами распоряжается создатель комнаты.',
  'err.bots_in_game': 'Нельзя менять состав ботов во время игры.',
  'err.no_bots': 'В комнате нет ботов.',
  'err.room_not_found': 'Комната не найдена. Проверьте код.',
  'err.kick_host_only': 'Только создатель комнаты может исключать.',
  'err.kick_in_game': 'Нельзя исключать во время игры.',
  'err.kick_self': 'Нельзя исключить самого себя.',
  'err.settings_host_only': 'Настройки меняет только создатель комнаты.',
  'err.settings_in_game': 'Нельзя менять настройки во время игры.',
  'err.min_players': 'Нужно минимум {min} игроков, сейчас {now}.',
  'err.max_players': 'Максимум {max} игроков.',
  'err.start_host_only': 'Начать игру может только создатель комнаты.',
  'err.already_started': 'Игра уже начата.',
  'err.phase_host_only': 'Переключать фазы может только ведущий.',
  'err.phase_bot_hosted': 'В этой комнате фазы переключает бот.',
  'err.not_running': 'Игра не идёт.',
  'err.restart_host_only': 'Новую партию начинает создатель комнаты.',
  'err.still_running': 'Игра ещё идёт.',
  'err.not_night': 'Сейчас не ночь.',
  'err.dead_no_action': 'Мёртвые не ходят.',
  'err.target_unavailable': 'Этот игрок недоступен.',
  'err.no_friendly_fire': 'Мафия не стреляет по своим.',
  'err.no_self_check': 'Себя проверять незачем.',
  'err.check_done': 'Проверка за эту ночь уже сделана.',
  'err.no_heal_twice': 'Одного и того же нельзя лечить две ночи подряд.',
  'err.no_night_action': 'У вашей роли нет ночного хода.',
  'err.not_voting': 'Сейчас не голосование.',
  'err.not_a_voter': 'Вы не участвуете в голосовании.',
  'err.candidate_no_vote': 'Кандидаты не голосуют в переголосовке.',
  'err.no_self_vote': 'Нельзя голосовать за себя.',
  'err.revote_candidates_only': 'В переголосовке можно выбирать только из кандидатов.',
  'err.discussion_only': 'Кнопка доступна только в обсуждении.',
  'err.not_participating': 'Вы не участвуете.',
  'err.not_in_room': 'Вы не в комнате.',
  'err.empty_message': 'Пустое сообщение.',
  'err.dead_silent': 'Мёртвые не говорят.',
  'err.night_silence': 'Ночью город молчит.',
  'err.bad_request': 'Некорректный запрос.',
  'err.auth_required': 'Сначала авторизация.',
  'err.bad_code': 'Код должен состоять из 5 символов.',
  'err.unknown_action': 'Неизвестное действие.',
  'err.action_unavailable': 'Действие недоступно.',
  'err.no_connection': 'Нет связи с сервером. Пытаюсь переподключиться…',
  'err.auth_missing': 'Нет данных авторизации Telegram.',
  'err.auth_no_token': 'На сервере не настроен BOT_TOKEN.',
  'err.auth_corrupt': 'Повреждённые данные авторизации.',
  'err.auth_no_hash': 'Отсутствует подпись.',
  'err.auth_bad_hash': 'Подпись не сходится.',
  'err.auth_expired': 'Данные авторизации устарели — перезапустите приложение.',
  'err.auth_bad_profile': 'Не удалось прочитать профиль.',
  'err.auth_no_user': 'В данных нет пользователя.',
};

const en = {
  'app.title': 'Mafia',
  'app.tagline': 'The classic party game for 5–12 people',
  'app.hello': 'Hi, {name}',
  'app.connecting': 'Connecting…',
  'app.reconnecting': 'Reconnecting…',
  'app.offline': 'Connection lost. Trying to reconnect…',
  'app.locked': 'Could not verify your Telegram login.\nOpen the game from the button in',
  'app.voiceHint': 'Voice makes it better — start a Telegram call and play alongside it.',

  'common.yes': 'Yes',
  'common.no': 'No',
  'common.enter': 'Join',
  'common.leave': 'Leave',
  'common.back': 'Back',
  'common.ready': 'ready',
  'common.you': 'you',
  'common.rules': 'How to play',
  'view.table': 'Table',
  'view.list': 'List',
  'common.hideRules': 'Hide rules',
  'common.channel': 'Follow the channel',
  'common.players': (n) => `${n} ${enPlural(n, 'player', 'players')}`,
  'common.playersShort': (n) => `${n} ${enPlural(n, 'player', 'players')}`,
  'common.alive': (n) => `${n} alive`,
  'common.rooms': (n) => `${n} ${enPlural(n, 'room', 'rooms')}`,
  'common.sec': (n) => `${n} sec`,
  'common.min': (n) => `${n} min`,

  'home.create': 'Create a room',
  'home.createNote': 'invite friends with a code',
  'home.openRooms': 'Open rooms',
  'home.openRoomsBtn': 'Open rooms',
  'home.roomsWaiting': (n) => `${n} ${n === 1 ? 'room is' : 'rooms are'} waiting`,
  'home.roomsEmpty': 'none yet',
  'rooms.title': 'Open rooms',
  'rooms.hint': 'Pick a room and jump in. The list refreshes itself.',
  'rooms.createOwn': 'Create your own room',
  'home.noRooms': 'No open rooms right now.',
  'home.noRoomsHint': 'Create one — others will see it.',
  'home.room': 'Room {code}',
  'home.needMore': (n) => `needs ${n} more ${enPlural(n, 'player', 'players')}`,
  'home.canStart': 'ready to start',
  'home.orCode': 'Or join by room code',
  'home.games': 'games',
  'home.winrate': 'wins',

  'home.bots': 'Play against bots',
  'home.botsNote': 'starts right away',
  'bots.title': 'Bots',
  'bots.add': 'Add a bot',
  'bots.remove': 'Remove a bot',
  'bots.count': (n) => `${n} ${enPlural(n, 'bot', 'bots')} at the table`,
  'bots.none': 'no bots',
  'bots.hint': 'Bots take the free seats and play on their own: they act at night, talk and vote.',
  'bots.badge': 'bot',
  'bots.solo': 'Game against bots',

  // Bot lines in the discussion: the server sends a code, the phrase is built here
  'bot.say.quiet': 'Everyone went quiet. Let us get to the point.',
  'bot.say.suspect': 'I do not like how {name} is playing this.',
  'bot.say.defend': 'I would not vote {name} — they have been open all day.',
  'bot.say.agree': 'Agreed with the last one. That tracks.',
  'bot.say.unsure': 'I still do not know who to vote for.',
  'bot.say.watch': 'Keep an eye on {name}, they keep quiet.',
  'bot.say.pressure': 'Let us decide, we are running out of time.',
  'bot.say.nothing': 'I have nothing from this night.',

  'lobby.code': 'Room code',
  'lobby.copy': 'Copy',
  'lobby.copied': 'Copied',
  'lobby.kick': 'Remove player',
  'lobby.invite': 'Invite friends',
  'lobby.inviteText': "Let's play Mafia! Room code: {code}",
  'lobby.players': 'Players',
  'lobby.of': 'of {max}',
  'lobby.waitingPlayer': 'Waiting for a player',
  'lobby.start': 'Start the game',
  'lobby.waitHost': 'Waiting for the host to start…',
  'lobby.settings': 'Game settings',
  'lobby.hideSettings': 'Hide settings',
  'lobby.creator': 'room creator',
  'lobby.hostNoRole': 'host, gets no role',
  'lobby.offline': 'offline, waiting for them',
  'lobby.composition': 'Line-up with {players}: {roles}',

  'set.host': 'Host',
  'set.hostBot': 'The bot runs the game, you play',
  'set.hostHuman': 'You run the game and get no role',
  'set.bot': 'Bot',
  'set.me': 'Me',
  'set.public': '🌍 Open room',
  'set.publicOn': 'Listed on the home screen, anyone can join',
  'set.publicOff': 'Code only — play with your own crowd',
  'set.doctor': '💉 Doctor',
  'set.doctorHint': 'Saves one player from the mafia each night',
  'set.sheriff': '🔎 Detective',
  'set.sheriffHint': 'Checks one player each night: mafia or not',
  'set.on': 'On',
  'set.off': 'Off',
  'set.maxPlayers': 'Max players',
  'set.tie': 'On a tied vote',
  'set.tieRevote': 'Run-off between the leaders',
  'set.tieNobody': 'Nobody is eliminated',
  'set.tieRandom': 'Random pick among leaders',
  'set.tieRevoteShort': 'Run-off',
  'set.tieNobodyShort': 'Nobody',
  'set.tieRandomShort': 'Random',
  'set.night': 'Night',
  'set.discussion': 'Discussion',
  'set.voting': 'Voting',
  'set.reveal': 'Reveal roles on death',
  'set.revealHint': 'Show what the eliminated player was',

  'phase.roles': 'Dealing roles',
  'phase.night': 'Night',
  'phase.day': 'Morning',
  'phase.discussion': 'Discussion',
  'phase.voting': 'Voting',
  'phase.revote': 'Run-off',
  'phase.verdict': 'Verdict',
  'phase.ended': 'Game over',

  'role.mafia': 'Mafia',
  'role.mafia.desc': 'At night you and your partners pick a victim. By day you pretend to be a townsperson.',
  'role.sheriff': 'Detective',
  'role.sheriff.desc': 'Each night you check one player and learn whether they are mafia.',
  'role.doctor': 'Doctor',
  'role.doctor.desc': 'Each night you save one player. If the mafia comes for them, they survive.',
  'role.civilian': 'Townsperson',
  'role.civilian.desc': 'No night powers. Your weapons are attention and persuasion.',
  'role.host': 'Host',
  'role.host.desc': 'You see every role and move the game along. You do not vote.',

  'game.dayN': 'Day {n}',
  'game.nightN': 'Night {n}',
  'game.rememberRole': 'Remember your role and show it to nobody',
  'game.partners': 'Your partners',
  'game.partnersMarked': 'Your partners are ringed in red.',
  'game.aloneMafia': 'You are the only mafioso. Tread carefully.',
  'game.dealt': 'Roles dealt',
  'game.wakeMafia': 'Wake the mafia and the detective',
  'game.nightMoves': 'Night moves',
  'game.cityAsleep': 'The town is asleep',
  'game.pickVictim': 'Choose a victim',
  'game.pickCheck': 'Check one player',
  'game.pickHeal': 'Who are you saving?',
  'game.youSleep': 'You are asleep. Wait for morning',
  'game.youSleepNote': 'You are a townsperson — just sleep. News comes in the morning.',
  'game.watching': 'You are watching. The town is asleep.',
  'game.mafiaTie': 'If the mafia picks different targets, the one with more votes dies.',
  'game.mafiaChat': 'Secret mafia chat…',
  'game.yourTarget': 'your target',
  'game.checkSent': 'Check submitted. You will see the result in the morning.',
  'game.yourChecks': 'Your checks',
  'game.isMafia': 'mafia',
  'game.notMafia': 'not mafia',
  'game.checkedMafia': '🔴 checked: mafia',
  'game.checkedClean': '🟢 checked: not mafia',
  'game.healedYesterday': 'healed last night — not allowed',
  'game.healing': 'you are saving them',
  'game.healRule': 'You cannot heal the same person two nights in a row. Healing yourself is allowed.',
  'game.healOn': 'You are at their bedside. If the mafia comes, they survive.',
  'game.beingHealed': '💉 healed',
  'game.cityWakes': 'The town wakes up',
  'game.killedTonight': 'killed last night',
  'game.executedByCity': 'executed by the town',
  'game.allSurvived': 'Everyone survived the night',
  'game.nobodyExecuted': 'The town executed nobody',
  'game.savedYou': '💉 The mafia came for you — you were in time. Only you know this.',
  'game.savedName': '💉 The mafia came for {name} — you were in time. Only you know this.',
  'game.discussFree': 'Talk it out — the host ends this phase',
  'game.discussTimed': 'Work out who looks like mafia',
  'game.yourTheory': 'Your theory…',
  'game.deadSilent': 'The dead stay silent',
  'game.readyToVote': 'Ready to vote ({done}/{total})',
  'game.youReady': '✓ You are ready ({done}/{total}) — undo',
  'game.votedOf': 'Voted: {done} of {total}',
  'game.votedCount': 'Voted {done} of {total}',
  'game.revoteNote': 'The vote was tied. The run-off is between the leaders only.',
  'game.revoteSub': 'Run-off between the leaders',
  'game.yourVote': 'your vote',
  'game.abstain': 'Abstain',
  'game.abstained': '✓ You abstained',
  'game.candidateNote': 'You are up for elimination and do not vote in this round.',
  'game.verdictSub': 'Vote result',
  'game.whatHappened': 'What happened',
  'game.hostView': 'You are the host: you see every role and move the game along.',
  'game.spectator': 'You are out, but you can watch until the end.',
  'game.inGame': 'in game',
  'game.noSignal': 'offline',
  'game.host': 'host',
  'game.diedNight': 'killed at night',
  'game.diedVote': 'executed by the town',
  'game.noMessages': 'No messages yet.',
  'game.write': 'Write…',

  'next.roles': 'Begin the first night →',
  'next.night': 'Wake the town →',
  'next.day': 'Start the discussion →',
  'next.discussion': 'Go to the vote →',
  'next.voting': 'Count the votes →',
  'next.revote': 'Count the votes →',
  'next.verdict': 'Begin the night →',
  'next.default': 'Next →',

  'over.mafiaWin': 'The mafia wins',
  'over.townWin': 'The town wins',
  'over.mafiaWinSub': 'The mafia matched the number of townspeople',
  'over.townWinSub': 'Every mafioso is out of the game',
  'over.youWon': '🎉 You are on the winning side',
  'over.youLost': 'Not your game this time',
  'over.mafiaTeam': 'Mafia ({n})',
  'over.townTeam': 'Town ({n})',
  'over.survived': ' · survived',
  'over.again': 'Play again',
  'over.waitHost': 'Waiting to see if the host starts another game…',
  'over.toMenu': 'Back to menu',

  'rules.title': 'Rules',
  'rules.mafia': 'The mafia',
  'rules.mafiaText': 'know each other and kill one townsperson every night.',
  'rules.doctor': 'The doctor',
  'rules.doctorText': 'saves one player each night — if the mafia came for them, they survive.',
  'rules.sheriff': 'The detective',
  'rules.sheriffText': 'checks one player each night: mafia or not.',
  'rules.civil': 'Townspeople',
  'rules.civilText': 'hunt the mafia with logic and argument.',
  'rules.counts': 'Roughly a third of the players are mafia: 5 players — 1 mafioso, 6–8 — 2, 9–11 — 3, 12 — 4. One doctor and one detective, both switched on in the room settings. Everyone else is a townsperson.',
  'rules.healRule': 'The doctor cannot heal the same person two nights in a row. Healing yourself is allowed.',
  'rules.night': 'At night',
  'rules.nightText': 'the town sleeps, the mafia agrees on a victim in their secret chat, the doctor saves someone, the detective checks a player.',
  'rules.morning': 'In the morning',
  'rules.morningText': 'the death is announced.',
  'rules.day': 'By day',
  'rules.dayText': 'everyone argues and votes. Whoever gets the most votes is eliminated. A tie triggers a run-off.',
  'rules.townWin': 'The town wins',
  'rules.townWinText': ' when no mafia is left.',
  'rules.mafiaWin': 'The mafia wins',
  'rules.mafiaWinText': ' when they match or outnumber the townspeople.',

  'comp.mafia': (n) => `${n} mafia`,
  'comp.sheriff': 'detective',
  'comp.doctor': 'doctor',
  'comp.civil': (n) => `${n} ${enPlural(n, 'townsperson', 'townspeople')}`,

  'log.game_started': 'The game has begun. Dealing roles.',
  'log.night_falls': 'Night {day}. The town falls asleep.',
  'log.killed': ({ name, role }, t) =>
    role ? `${name} was killed in the night (${t(`roleLower.${role}`)}).` : `${name} was killed in the night.`,
  'log.nobody_died': 'Nobody died last night.',
  'log.voting_started': 'The vote has begun.',
  'log.nobody_voted': 'Nobody voted — the town executed no one.',
  'log.tie_revote': 'Tied vote: {names}. Run-off.',
  'log.tie_nobody': 'The vote was tied — nobody is eliminated.',
  'log.executed': ({ name, role }, t) =>
    role ? `${name} was executed by the town (${t(`roleLower.${role}`)}).` : `${name} was executed by the town.`,
  'log.win_mafia': 'The mafia wins: they match the townspeople in number.',
  'log.win_town': 'The town wins: every mafioso is out.',

  'roleLower.mafia': 'mafia',
  'roleLower.sheriff': 'detective',
  'roleLower.doctor': 'doctor',
  'roleLower.civilian': 'townsperson',

  'err.game_running': 'The game has already started — you cannot join.',
  'err.game_over': 'This game is already finished.',
  'err.room_full': 'The room is full.',
  'err.bots_host_only': 'Only the room creator manages bots.',
  'err.bots_in_game': 'Bots cannot be added or removed mid-game.',
  'err.no_bots': 'There are no bots in the room.',
  'err.room_not_found': 'Room not found. Check the code.',
  'err.kick_host_only': 'Only the room creator can remove players.',
  'err.kick_in_game': 'You cannot remove players during a game.',
  'err.kick_self': 'You cannot remove yourself.',
  'err.settings_host_only': 'Only the room creator changes the settings.',
  'err.settings_in_game': 'Settings cannot change during a game.',
  'err.min_players': 'At least {min} players are needed, currently {now}.',
  'err.max_players': 'At most {max} players.',
  'err.start_host_only': 'Only the room creator can start the game.',
  'err.already_started': 'The game has already started.',
  'err.phase_host_only': 'Only the host can move the game along.',
  'err.phase_bot_hosted': 'In this room the bot runs the phases.',
  'err.not_running': 'The game is not running.',
  'err.restart_host_only': 'The room creator starts a new game.',
  'err.still_running': 'The game is still going.',
  'err.not_night': 'It is not night.',
  'err.dead_no_action': 'The dead do not act.',
  'err.target_unavailable': 'That player is unavailable.',
  'err.no_friendly_fire': 'The mafia does not shoot its own.',
  'err.no_self_check': 'No point checking yourself.',
  'err.check_done': 'You have already checked someone tonight.',
  'err.no_heal_twice': 'You cannot heal the same person two nights in a row.',
  'err.no_night_action': 'Your role has no night move.',
  'err.not_voting': 'It is not voting time.',
  'err.not_a_voter': 'You are not taking part in the vote.',
  'err.candidate_no_vote': 'Candidates do not vote in the run-off.',
  'err.no_self_vote': 'You cannot vote for yourself.',
  'err.revote_candidates_only': 'In the run-off you can only pick a candidate.',
  'err.discussion_only': 'That button works during the discussion only.',
  'err.not_participating': 'You are not taking part.',
  'err.not_in_room': 'You are not in a room.',
  'err.empty_message': 'Empty message.',
  'err.dead_silent': 'The dead stay silent.',
  'err.night_silence': 'The town is silent at night.',
  'err.bad_request': 'Malformed request.',
  'err.auth_required': 'Sign in first.',
  'err.bad_code': 'The code must be 5 characters.',
  'err.unknown_action': 'Unknown action.',
  'err.action_unavailable': 'That action is unavailable.',
  'err.no_connection': 'No connection to the server. Reconnecting…',
  'err.auth_missing': 'No Telegram login data.',
  'err.auth_no_token': 'BOT_TOKEN is not configured on the server.',
  'err.auth_corrupt': 'Corrupted login data.',
  'err.auth_no_hash': 'Signature missing.',
  'err.auth_bad_hash': 'Signature does not match.',
  'err.auth_expired': 'Login data has expired — reopen the app.',
  'err.auth_bad_profile': 'Could not read the profile.',
  'err.auth_no_user': 'No user in the login data.',
};

export const DICTS = { ru, en };
export const LANGS = ['ru', 'en'];

/** Язык по умолчанию: сохранённый выбор, иначе язык Telegram. */
export function detectLang() {
  try {
    const saved = localStorage.getItem(LANG_KEY);
    if (saved && LANGS.includes(saved)) return saved;
  } catch { /* приватный режим */ }

  const code = tg?.initDataUnsafe?.user?.language_code || navigator?.language || '';
  return /^(ru|uk|be|kk|uz|ky|tg|az|hy)/i.test(code) ? 'ru' : 'en';
}

/** Достаёт перевод и подставляет значения. */
export function translate(lang, key, params) {
  const dict = DICTS[lang] || DICTS.ru;
  const value = dict[key] ?? DICTS.ru[key];
  if (value === undefined) return key; // не нашли — покажем ключ, это заметно

  const self = (k, p) => translate(lang, k, p);

  if (typeof value === 'function') {
    // Для чисел удобнее звать t('common.players', 3), поэтому берём и голое число
    if (typeof params === 'number') return value(params, self);
    return value(params || {}, self);
  }

  if (!params || typeof params !== 'object') return value;
  return value.replace(/\{(\w+)\}/g, (m, name) => (params[name] ?? m));
}
